language: ruby

sudo: false
dist: precise

cache: bundler

addons:
  code_climate:
    repo_token:
      secure: "oe4xWJO8lDmY61zPZX8659VwOMrEHILd25o6X369E7z+0BW/IjVRAC82uxFRKmDwYoXSFqlctISpE6FMejEdlLtRU+YjPPzCaGZUUlLw1s3fc5MfbfnLF3BBy1somz+sLCpT71kmfnG2X2tHfqV7NfhbZYkRY2xDt5QXpiiquMY="

before_install:
  - gem install bundler

rvm:
  - 2.4.4
  - 2.5.1
  - 2.6.0
  - ruby-head

script:
  - bundle exec rake test
  - bundle exec codeclimate-test-reporter

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6f2391f05f5fd4d55bf0
